//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace LearningKanji.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KanjiObj", Namespace="http://schemas.datacontract.org/2004/07/LearningKanji.Web")]
    public partial class KanjiObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _mChineseField;
        
        private string _mHiraganaField;
        
        private int _mIDField;
        
        private string _mLessionIDField;
        
        private string _mLessionNameField;
        
        private int _mOrderField;
        
        private string _mVietnamesField;
        
        private string _mVocabularyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _mChinese {
            get {
                return this._mChineseField;
            }
            set {
                if ((object.ReferenceEquals(this._mChineseField, value) != true)) {
                    this._mChineseField = value;
                    this.RaisePropertyChanged("_mChinese");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _mHiragana {
            get {
                return this._mHiraganaField;
            }
            set {
                if ((object.ReferenceEquals(this._mHiraganaField, value) != true)) {
                    this._mHiraganaField = value;
                    this.RaisePropertyChanged("_mHiragana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _mID {
            get {
                return this._mIDField;
            }
            set {
                if ((this._mIDField.Equals(value) != true)) {
                    this._mIDField = value;
                    this.RaisePropertyChanged("_mID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _mLessionID {
            get {
                return this._mLessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this._mLessionIDField, value) != true)) {
                    this._mLessionIDField = value;
                    this.RaisePropertyChanged("_mLessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _mLessionName {
            get {
                return this._mLessionNameField;
            }
            set {
                if ((object.ReferenceEquals(this._mLessionNameField, value) != true)) {
                    this._mLessionNameField = value;
                    this.RaisePropertyChanged("_mLessionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _mOrder {
            get {
                return this._mOrderField;
            }
            set {
                if ((this._mOrderField.Equals(value) != true)) {
                    this._mOrderField = value;
                    this.RaisePropertyChanged("_mOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _mVietnames {
            get {
                return this._mVietnamesField;
            }
            set {
                if ((object.ReferenceEquals(this._mVietnamesField, value) != true)) {
                    this._mVietnamesField = value;
                    this.RaisePropertyChanged("_mVietnames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _mVocabulary {
            get {
                return this._mVocabularyField;
            }
            set {
                if ((object.ReferenceEquals(this._mVocabularyField, value) != true)) {
                    this._mVocabularyField = value;
                    this.RaisePropertyChanged("_mVocabulary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LearningKanji.Web", ConfigurationName="ServiceReference1.IKanjiService")]
    public interface IKanjiService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="LearningKanji.Web/IKanjiService/GetListKanji", ReplyAction="LearningKanji.Web/IKanjiService/GetListKanjiResponse")]
        System.IAsyncResult BeginGetListKanji(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<LearningKanji.ServiceReference1.KanjiObj> EndGetListKanji(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="LearningKanji.Web/IKanjiService/GetLessionName", ReplyAction="LearningKanji.Web/IKanjiService/GetLessionNameResponse")]
        System.IAsyncResult BeginGetLessionName(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.Dictionary<int, string> EndGetLessionName(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKanjiServiceChannel : LearningKanji.ServiceReference1.IKanjiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListKanjiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetListKanjiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<LearningKanji.ServiceReference1.KanjiObj> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<LearningKanji.ServiceReference1.KanjiObj>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLessionNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLessionNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.Dictionary<int, string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.Dictionary<int, string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KanjiServiceClient : System.ServiceModel.ClientBase<LearningKanji.ServiceReference1.IKanjiService>, LearningKanji.ServiceReference1.IKanjiService {
        
        private BeginOperationDelegate onBeginGetListKanjiDelegate;
        
        private EndOperationDelegate onEndGetListKanjiDelegate;
        
        private System.Threading.SendOrPostCallback onGetListKanjiCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLessionNameDelegate;
        
        private EndOperationDelegate onEndGetLessionNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetLessionNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public KanjiServiceClient() {
        }
        
        public KanjiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KanjiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KanjiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KanjiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetListKanjiCompletedEventArgs> GetListKanjiCompleted;
        
        public event System.EventHandler<GetLessionNameCompletedEventArgs> GetLessionNameCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LearningKanji.ServiceReference1.IKanjiService.BeginGetListKanji(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetListKanji(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<LearningKanji.ServiceReference1.KanjiObj> LearningKanji.ServiceReference1.IKanjiService.EndGetListKanji(System.IAsyncResult result) {
            return base.Channel.EndGetListKanji(result);
        }
        
        private System.IAsyncResult OnBeginGetListKanji(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((LearningKanji.ServiceReference1.IKanjiService)(this)).BeginGetListKanji(callback, asyncState);
        }
        
        private object[] OnEndGetListKanji(System.IAsyncResult result) {
            System.Collections.Generic.List<LearningKanji.ServiceReference1.KanjiObj> retVal = ((LearningKanji.ServiceReference1.IKanjiService)(this)).EndGetListKanji(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetListKanjiCompleted(object state) {
            if ((this.GetListKanjiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListKanjiCompleted(this, new GetListKanjiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetListKanjiAsync() {
            this.GetListKanjiAsync(null);
        }
        
        public void GetListKanjiAsync(object userState) {
            if ((this.onBeginGetListKanjiDelegate == null)) {
                this.onBeginGetListKanjiDelegate = new BeginOperationDelegate(this.OnBeginGetListKanji);
            }
            if ((this.onEndGetListKanjiDelegate == null)) {
                this.onEndGetListKanjiDelegate = new EndOperationDelegate(this.OnEndGetListKanji);
            }
            if ((this.onGetListKanjiCompletedDelegate == null)) {
                this.onGetListKanjiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListKanjiCompleted);
            }
            base.InvokeAsync(this.onBeginGetListKanjiDelegate, null, this.onEndGetListKanjiDelegate, this.onGetListKanjiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LearningKanji.ServiceReference1.IKanjiService.BeginGetLessionName(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLessionName(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.Dictionary<int, string> LearningKanji.ServiceReference1.IKanjiService.EndGetLessionName(System.IAsyncResult result) {
            return base.Channel.EndGetLessionName(result);
        }
        
        private System.IAsyncResult OnBeginGetLessionName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((LearningKanji.ServiceReference1.IKanjiService)(this)).BeginGetLessionName(callback, asyncState);
        }
        
        private object[] OnEndGetLessionName(System.IAsyncResult result) {
            System.Collections.Generic.Dictionary<int, string> retVal = ((LearningKanji.ServiceReference1.IKanjiService)(this)).EndGetLessionName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLessionNameCompleted(object state) {
            if ((this.GetLessionNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLessionNameCompleted(this, new GetLessionNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLessionNameAsync() {
            this.GetLessionNameAsync(null);
        }
        
        public void GetLessionNameAsync(object userState) {
            if ((this.onBeginGetLessionNameDelegate == null)) {
                this.onBeginGetLessionNameDelegate = new BeginOperationDelegate(this.OnBeginGetLessionName);
            }
            if ((this.onEndGetLessionNameDelegate == null)) {
                this.onEndGetLessionNameDelegate = new EndOperationDelegate(this.OnEndGetLessionName);
            }
            if ((this.onGetLessionNameCompletedDelegate == null)) {
                this.onGetLessionNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLessionNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetLessionNameDelegate, null, this.onEndGetLessionNameDelegate, this.onGetLessionNameCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LearningKanji.ServiceReference1.IKanjiService CreateChannel() {
            return new KanjiServiceClientChannel(this);
        }
        
        private class KanjiServiceClientChannel : ChannelBase<LearningKanji.ServiceReference1.IKanjiService>, LearningKanji.ServiceReference1.IKanjiService {
            
            public KanjiServiceClientChannel(System.ServiceModel.ClientBase<LearningKanji.ServiceReference1.IKanjiService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetListKanji(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetListKanji", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<LearningKanji.ServiceReference1.KanjiObj> EndGetListKanji(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<LearningKanji.ServiceReference1.KanjiObj> _result = ((System.Collections.Generic.List<LearningKanji.ServiceReference1.KanjiObj>)(base.EndInvoke("GetListKanji", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLessionName(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetLessionName", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.Dictionary<int, string> EndGetLessionName(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.Dictionary<int, string> _result = ((System.Collections.Generic.Dictionary<int, string>)(base.EndInvoke("GetLessionName", _args, result)));
                return _result;
            }
        }
    }
}
